frase1='Curso em Vídeo Python'
frase2='  Aprenda Python  '
print('Frase 1: Curso em Vídeo Python')
print(frase1[1:9])
print(frase1[1::2])
print('')
print(len(frase1))
print('')
print(frase1.count('o'))
print('')
print(frase1.find('deo'))
print('')
print('Curso' in frase1)
print('')
print(frase1.upper())
print('')
print(frase1.lower())
print('')
print(frase1.capitalize())
print('')
print(frase1.title())
print('Frase 2:  Aprenda Python   ')
print('')
print(frase2.strip())
print('')
print(frase2.rstrip())
print('')
print(frase2.lstrip())
print('Frase 1: Curso em Vídeo Python')
print('')
print(frase1.split())
print('-'.join(frase1))
