#Crie um programa que leia um número e mostre sua tabuada:
número = int(input('Digite um número: '))
print('-=-'*20)
print(f'{número} x {1:2} = {número * 1}')
print(f'{número} x {2:2} = {número * 2}')
print(f'{número} x {3:2} = {número * 3}')
print(f'{número} x {4:2} = {número * 4}')
print(f'{número} x {5:2} = {número * 5}')
print(f'{número} x {6:2} = {número * 6}')
print(f'{número} x {7:2} = {número * 7}')
print(f'{número} x {8:2} = {número * 8}')
print(f'{número} x {9:2} = {número * 9}')
print(f'{número} x {10:2} = {número * 10}')
print('-=-'*20)
